import Head from 'next/head';

import RegistrForm from '../app/components/RegistrForm';

export default function Home() {
  return (
    <>
      <Head>
        <title>Registration Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegistrForm />
    </>
  );
}
